server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:

  servlet:
    multipart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/blog-test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    h2:
      console:
        enabled: true

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: noreply.bloggero@gmail.com
    password: qzzi ydsw ktbs ubbb
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    open-in-view: false

cloudinary:
  cloudName: dqnjcfj2k
  apiKey: 797382638172868
  apiSecret: 2zx4q_dhE-PtActjFHb06GadC0Q
  secure: true


logging:
  level:
    hu.progmasters: info
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"